### ISSUE TITLE
Monitoring and plotting results

### ISSUE THREAD

**Issue by TheMnBN** [LinZichuan/emdqn#1]
Hi, do you have an usage example for plotting results with this code? If I don't use Container from the azure_util module then only a text file with timesteps and averaged reward would be saved.

Edit: I figured out about results logging with SimpleMonitor but I would appreciate an use case of saving and logging with Container.
Thank you kindly!

Dan

**Comment by LinZichuan** [comment]
> Hi, do you have an usage example for plotting results with this code? If I don't use Container from the azure_util module then only a text file with timesteps and averaged reward would be saved.
> 
> Edit: I figured out about results logging with SimpleMonitor but I would appreciate an use case of saving and logging with Container.
> Thank you kindly!
> 
> Dan

Hi, you can read time steps x and scores y from the result files and use matplotlib.pyplot.plot(x, y) to get training curves.
